# Generated by Django 5.2 on 2025-05-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ingredient_recipe_recipeingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='course',
            field=models.CharField(choices=[('Appetizers', 'Appetizers'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert')], max_length=20),
        ),
    ]
