# Generated by Django 5.2 on 2025-05-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_recipe_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
